version: '2'

# shamelessly repurposed from
# https://github.com/buildbot/buildbot-docker-example-config/blob/master/simple/docker-compose.yml

services:
  buildbot:
    image: buildbot/buildbot-master:master
    environment:
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8080/
      - BUILDBOT_WEB_PORT=tcp:8080
    ports:
      - "8080:8080"
    volumes:
      - ./farm/buildbot:/var/lib/buildbot
